# Generated by Django 2.1.1 on 2020-02-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgInfo',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('img_url', models.CharField(max_length=128)),
                ('remark', models.IntegerField(choices=[(1, 'internet'), (2, 'local'), (3, 'others')])),
            ],
        ),
    ]
